-- drop all constraints to make sure we don't have any relationship errors on creation
ALTER TABLE IF EXISTS jobs DROP CONSTRAINT jobs_business_id_fkey;
ALTER TABLE IF EXISTS payroll DROP CONSTRAINT payroll_business_id_fkey;
ALTER TABLE IF EXISTS payroll DROP CONSTRAINT payroll_user_id_fkey;

-- drop all tables to rebuild them
DROP TABLE IF EXISTS businesses;
DROP TABLE IF EXISTS users;
DROP TABLE IF EXISTS jobs;
DROP TABLE IF EXISTS payroll;

-- create fresh tables
CREATE TABLE "businesses" (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name varchar NOT NULL,
  address varchar,
  phone varchar NOT NULL,
  created_at timestamp DEFAULT (now())
);

CREATE TABLE "users" (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  first_name varchar NOT NULL,
  last_name varchar NOT NULL,
  phone varchar,
  email varchar NOT NULL,
  password varchar NOT NULL,
  created_at timestamp DEFAULT (now())
);

CREATE TABLE "jobs" (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name varchar NOT NULL,
  address varchar,
  labor_cost int,
  created_at timestamp DEFAULT (now()),
  business_id int NOT NULL REFERENCES businesses(id)
);

CREATE TABLE "payroll" (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  hours int,
  submission_date date NOT NULL,
  created_at timestamp DEFAULT (now()),
  business_id int NOT NULL REFERENCES businesses(id),
  user_id int NOT NULL REFERENCES users(id)
);
