CREATE TABLE "businesses" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar NOT NULL,
  "address" varchar,
  "phone" varchar NOT NULL,
  "created_at" timestamp DEFAULT (now())
);

CREATE TABLE "users" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "first_name" varchar NOT NULL,
  "last_name" varchar NOT NULL,
  "phone" varchar,
  "email" varchar NOT NULL,
  "created_at" timestamp DEFAULT (now())
);

CREATE TABLE "jobs" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar NOT NULL,
  "address" varchar,
  "business_id" int NOT NULL,
  "labor_cost" int,
  "created_at" timestamp DEFAULT (now())
);

CREATE TABLE "payroll" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "hours" int,
  "user_id" int NOT NULL,
  "submission_date" date NOT NULL,
  "business_id" int NOT NULL,
  "created_at" timestamp DEFAULT (now())
);

ALTER TABLE "jobs" ADD FOREIGN KEY ("business_id") REFERENCES "businesses" ("id");

ALTER TABLE "payroll" ADD FOREIGN KEY ("business_id") REFERENCES "businesses" ("id");

ALTER TABLE "payroll" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id");
